[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
solc = '0.8.30'
optimizer_runs = 200

[fuzz]
runs = 500
max_test_rejects = 65536

remappings= [
    '@openzeppelin=lib/openzeppelin-contracts-upgradable/contracts',
    '@forge-std=lib/forge-std/src',
    '@contract=src/contracts/',
    '@test=test'
]